name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Définir les variables pour le tag Docker
      - name: Set up Docker image tag
        id: vars
        run: |
          echo "IMAGE_TAG=7shinomiya/flask-app-swarm:${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Étape 4 : Construire et pousser l'image Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
        - name: Deploy updated image to Docker Swarm
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: rnhnf-93-2-110-186.a.free.pinggy.link
            port: 35665
            username: root
            password: ${{ secrets.PINGGY_PASSWORD }}
            script: |
              echo "Deploying image: $IMAGE_TAG"
              docker service update --image 7shinomiya/flask-app-swarm:af45175 flask-app
              echo "Starting Pinggy tunnel..."
              ssh -p 35665 -R0:127.0.0.1:5000 root@rnhnf-93-2-110-186.a.free.pinggy.link
