name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Définir les variables pour le tag Docker
      - name: Set up Docker image tag
        id: vars
        run: |
          echo "IMAGE_TAG=7shinomiya/flask-app-swarm:${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Étape 4 : Construire et pousser l'image Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Étape 1 : Se connecter au manager via SSH et mettre à jour le service
      - name: Update Docker Swarm service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.NGROK_HOST }}
          port: ${{ secrets.NGROK_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker service update --image $IMAGE_TAG flask-app-service
