name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Remplace par la branche que tu veux surveiller

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Pull de l'image existante depuis le registre Docker
      - name: Pull existing image
        run: |
          docker pull your-docker-repo/your-image:latest || true

      # Étape 4 : Construire l'image Docker
      - name: Build the Docker image
        run: |
          docker build -t your-docker-repo/your-image:latest .

      # Étape 5 : Pousser l'image vers le registre Docker
      - name: Push the Docker image
        run: |
          docker push your-docker-repo/your-image:latest
