name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change si tu utilises une autre branche

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Définir les variables pour le tag Docker
      - name: Set up Docker image tag
        id: vars
        run: |
          echo "IMAGE_TAG=unknown64/flask-app-swarm:${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Étape 4 : Construire l'image Docker
      - name: Build the Docker image
        run: |
          docker build -t $IMAGE_TAG .

      # Étape 5 : Pousser l'image vers Docker Hub
      - name: Push the Docker image
        run: |
          docker push $IMAGE_TAG

      # Étape 6 : Taguer et pousser comme "latest" (optionnel)
      - name: Tag and push as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $IMAGE_TAG unknown64/flask-app-swarm:latest
          docker push unknown64/flask-app-swarm:latest
